# Generated by Django 4.2.11 on 2024-03-15 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=15)),
                ('LastName', models.CharField(max_length=20)),
                ('Course', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=30)),
                ('Phone_number', models.PositiveIntegerField()),
                ('State_of_origin', models.CharField(max_length=20)),
                ('Date_of_birth', models.DateField()),
                ('Registration_date', models.DateField()),
                ('Starting_date', models.DateField()),
                ('Ending_date', models.DateField()),
                ('Address', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
